FROM php:8.1-apache
RUN apt -yqq update

WORKDIR /var/www

## Libraries
RUN apt -yqq install libxml2-dev
RUN apt -yqq install zlib1g-dev
RUN apt -yqq install libpng-dev
RUN apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libldap2-dev

## Dependencies
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install mysqli
##RUN docker-php-ext-install xml
##RUN docker-php-ext-install zip

## GIT
RUN apt-get install git -y

## Others
RUN apt-get install vim -y
RUN a2enmod rewrite

#RUN cd /var/www/html && git clone https://github.com/michelpl/message-management-api.git .

ENV APACHE_DOCUMENT_ROOT /var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

RUN mkdir /var/www/html/public/
RUN touch /var/www/html/public/index.php

##COMPOSER
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
RUN php composer-setup.php
#RUN php -r "unlink('composer-setup.php');"

##RUN cp /var/www/html/.env.example /var/www/html/.env

#RUN php composer.phar update -vvv

##COPY .env /var/www/html
#RUN php artisan key:generate

## Laravel
#RUN php composer.phar create-project laravel/laravel hiring-challenge

## File create and permissions
#RUN find /var/www/html/ -type d -exec chmod 775 {} \;
#RUN find /var/www/html/ -type f -exec chmod 664 {} \;
#RUN chown -R www-data:root /var/www/html/
#RUN mkdir /var/www/html/public
#RUN touch /var/www/html/public/index.php